### ISSUE TITLE
renren-fast

### ISSUE THREAD

**Issue by qifengle1998** [qifengle1998/LifeTime#67]
# 任务概览
- [x] 成功运行renren-fast服务
---
- [x] 将服务成功注册到注册中心
- [x] 通过配置中心来管理服务的配置

**Comment by qifengle1998** [comment]
报错
 create config service error!

**Comment by qifengle1998** [comment]
> 报错 create config service error!

纠结是否是lombok插件没安装，但是2021版本以后已经内置了，不需要安装
花了点时间了解了jrebel，暂时用不到

**Comment by qifengle1998** [comment]
> 报错 create config service error!

尝试浏览注册中心、配置中心视频，看是否有没有配置的地方

**Comment by qifengle1998** [comment]
> > 报错 create config service error!
> 
> 尝试浏览注册中心、配置中心视频，看是否有没有配置的地方

不行，启动配置中心以后，就没啥可以改的了

**Comment by qifengle1998** [comment]
renren-fast跑不起来，
尝试了另外两个模块，coupon和member，能够成功跑起来了， 但是跳转以后报错
![image](https://user-images.githubusercontent.com/37429029/175305017-161535c8-5af6-4f04-81bd-58724112f12f.png)
仔细观看教程视频，发现雷神也是这样的，需要另外输入请求
![image](https://user-images.githubusercontent.com/37429029/175305122-49c5a374-9942-4fc8-8443-ebda9e58d915.png)
成功跑起一个服务

**Comment by qifengle1998** [comment]
使用2.1.0版本，成功将服务注册到Nacos，yse！！！！
![image](https://user-images.githubusercontent.com/37429029/175313681-8c52a204-0cd7-4ed2-ac4b-ef3205ad85e3.png)

**Comment by qifengle1998** [comment]
配置中心依然无法热部署

**Comment by qifengle1998** [comment]
> 配置中心依然无法热部署

尝试重启nacos，无果

**Comment by qifengle1998** [comment]
> 配置中心依然无法热部署

尝试加入spring-cloud-starter-bootstrap依赖，报错。
rebuild项目，报错“java: 程序包com.baomidou.mybatisplus.extension.service不存在”

**Comment by qifengle1998** [comment]
> > 配置中心依然无法热部署
> 
> 尝试加入spring-cloud-starter-bootstrap依赖，报错。 rebuild项目，报错“java: 程序包com.baomidou.mybatisplus.extension.service不存在”

https://www.jianshu.com/p/9ae4710939df
通过setting->maven->Runner,勾选：Delegate ide build/run actions to Maven，再次运行就不会再出现这样的问题了
但是另外报错
“Failed to execute goal on project gulimall-coupon: Could not resolve dependencies”
又通过把这个设置关闭解决

**Comment by qifengle1998** [comment]
发现自己的maven仓库配置有问题
![image](https://user-images.githubusercontent.com/37429029/175474886-ebd92661-f994-484c-8de8-e93136820d81.png)

**Comment by qifengle1998** [comment]
不是依赖、版本的问题，把bootstrap里面关于配置分组的部分注释掉就行了
![image](https://user-images.githubusercontent.com/37429029/175753301-4f8f398c-6a2b-4c22-8e32-2e6114242948.png)

**Comment by qifengle1998** [comment]
[(12条消息) idea中service启动类是灰色，而且启动类经常自动消失解决方法_隔壁老赵的博客-CSDN博客_idea services 灰色](https://blog.csdn.net/weixin_42661168/article/details/115365200)

**Comment by qifengle1998** [comment]
> 报错 create config service error!

- [(12条消息) bug_ renren-fast注册到 nacos上_飞花落雨的博客-CSDN博客](https://blog.csdn.net/u013372493/article/details/114303329)
- [(12条消息) Maven的排除依赖、归类依赖、优化依赖_c.的博客-CSDN博客_排除依赖](https://blog.csdn.net/cckevincyh/article/details/73512722)

尝试文中提到的方式，将nacos配置中心的依赖排除

**Comment by qifengle1998** [comment]
> > 报错 create config service error!
> 
> * [(12条消息) bug_ renren-fast注册到 nacos上_飞花落雨的博客-CSDN博客](https://blog.csdn.net/u013372493/article/details/114303329)
> * [(12条消息) Maven的排除依赖、归类依赖、优化依赖_c.的博客-CSDN博客_排除依赖](https://blog.csdn.net/cckevincyh/article/details/73512722)
> 
> 尝试文中提到的方式，将nacos配置中心的依赖排除

Error creating bean with name 'scheduleJobController': Unsatisfied dependency expressed through field 'scheduleJobService'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'scheduleJobService': Invocation of init method failed; nested exception is io.renren.common.exception.RRException: 获取定时任务CronTrigger出现异常
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:596)

**Comment by qifengle1998** [comment]
> > > 报错 create config service error!
> > 
> > 
> > 
> > * [(12条消息) bug_ renren-fast注册到 nacos上_飞花落雨的博客-CSDN博客](https://blog.csdn.net/u013372493/article/details/114303329)
> > * [(12条消息) Maven的排除依赖、归类依赖、优化依赖_c.的博客-CSDN博客_排除依赖](https://blog.csdn.net/cckevincyh/article/details/73512722)
> > 
> > 尝试文中提到的方式，将nacos配置中心的依赖排除
> 
> Error creating bean with name 'scheduleJobController': Unsatisfied dependency expressed through field 'scheduleJobService'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'scheduleJobService': Invocation of init method failed; nested exception is io.renren.common.exception.RRException: 获取定时任务CronTrigger出现异常 at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:596)

按照这个贴子，清空定时作业表，成功
[renren-fast运行有报错 - 人人开源社区](https://www.renren.io/detail/13914)

**Comment by qifengle1998** [comment]
yun'xi运行前端项目后，没有验证码，并且报错
`Failure obtaining db row lock: Table 'gulimall_admin.QRTZ_LOCKS' doesn't exist`
![image](https://user-images.githubusercontent.com/37429029/175756528-9157b142-d64b-4717-b5cc-e86a34adee78.png)

**Comment by qifengle1998** [comment]
常见Vim命令
[VIM中的保存和退出、VIM退出命令、如何退出vim编辑、VIM命令大全 - 简书](https://www.jianshu.com/p/0009bf462f15)

**Comment by qifengle1998** [comment]
> yun'xi运行前端项目后，没有验证码，并且报错 `Failure obtaining db row lock: Table 'gulimall_admin.QRTZ_LOCKS' doesn't exist` ![image](https://user-images.githubusercontent.com/37429029/175756528-9157b142-d64b-4717-b5cc-e86a34adee78.png)

问题原因是因为linux中的mysql，对表的大小写敏感。
而我采用[(12条消息) 解决Linux docker中的mysql区分大小写问题_与李的博客-CSDN博客_docker mysql 区分大小写](https://blog.csdn.net/qq_37171817/article/details/108466305?utm_relevant_index=5)并没有解决问题

最后发现我的文件名是 my.conf 而应该采用my.conf,所以我要删除容器，重新创建

**Comment by qifengle1998** [comment]
遇到docker一直restarting
![image](https://user-images.githubusercontent.com/37429029/175763798-133e1737-e6d7-41d9-9dda-d7fe8c5882b5.png)

**Comment by qifengle1998** [comment]
> 遇到docker一直restarting ![image](https://user-images.githubusercontent.com/37429029/175763798-133e1737-e6d7-41d9-9dda-d7fe8c5882b5.png) 去掉目录挂载部分，发现可以正常运行

[(12条消息) 关于docker -v 挂载后服务无法启动问题。_weixin_30241919的博客-CSDN博客](https://blog.csdn.net/weixin_30241919/article/details/94805843)
尝试了三种办法，都失败了。
最后把原来 /mydata/mysql目录删掉就成功了

**Comment by qifengle1998** [comment]
> > 遇到docker一直restarting ![image](https://user-images.githubusercontent.com/37429029/175763798-133e1737-e6d7-41d9-9dda-d7fe8c5882b5.png) 去掉目录挂载部分，发现可以正常运行
> 
> [(12条消息) 关于docker -v 挂载后服务无法启动问题。_weixin_30241919的博客-CSDN博客](https://blog.csdn.net/weixin_30241919/article/details/94805843) 尝试了三种办法，都失败了。 最后把原来 /mydata/mysql目录删掉就成功了

我再次测试就发现，竟然真的是因为我增加了一行配置 lower_case_table_names
就直接导致整个容器没法启动了
[(12条消息) docker安装Mysql8.0的坑之lower_case_table_names_goodjob110的博客-CSDN博客](https://blog.csdn.net/lazycheerup/article/details/122701141)

**Comment by qifengle1998** [comment]
发现自己虚拟机的ip地址过一段时间就递增一次

**Comment by qifengle1998** [comment]
![image](https://user-images.githubusercontent.com/37429029/175773911-e1810efb-87ad-47d6-9442-8fc7813858d2.png)
重新初始化了数据库，也没有报错了，但是依旧没有验证码

**Comment by qifengle1998** [comment]
1. 解决跨域问题，无果
[(12条消息) renren-fast后端代码版本升级踩坑记录（四）_群子7559的博客-CSDN博客](https://blog.csdn.net/qun7559/article/details/122910758)
2. 修改前端访问的后端地址，无果
[(12条消息) # Vue 配置前端后端路由地址_爱码代码的喵的博客-CSDN博客_vue项目配置后端地址](https://blog.csdn.net/qq_37248504/article/details/103208656)

**Comment by qifengle1998** [comment]
> ![image](https://user-images.githubusercontent.com/37429029/175773911-e1810efb-87ad-47d6-9442-8fc7813858d2.png) 重新初始化了数据库，也没有报错了，但是依旧没有验证码

先推进网关这一课，看看问题会不会在后续解决

**Comment by qifengle1998** [comment]
继续学习后面的三级分类
跟着学习了 网关，发现前端的请求时发送给网关的
在网关处设置了路由规则、路径重写，跨域配置以后就可以正常登录了，成了！！！！！！！！！
![image](https://user-images.githubusercontent.com/37429029/175804562-af53fa6b-8ec6-487f-b7c7-c49eb72ce58b.png)
